version: "3.8"

x-config:
  user: &user ${UID:?UID not set}:${GID:?GID not set}
  volumes:
    user:
      - &home ${HOME:?Home dir not set}:${HOME:?Home dir not set}
      - &group /etc/group:/etc/group:ro
      - &passwd /etc/passwd:/etc/passwd:ro
      - &shadow /etc/shadow:/etc/shadow:ro
    app:
      - &app
        type: bind
        source: ./src
        target: /app

services:
  php:
    build: ./docker/php
    user: *user
    working_dir: /app
    environment:
      XDEBUG_CONFIG: remote_host=${IP:-host.docker.internal} remote_enable=1 extended_info=1
      PHP_IDE_CONFIG: serverName=Docker
    volumes:
      - *group
      - *passwd
      - *shadow
      - *home
      - *app
      - ./docker/php/conf/ports.conf:/etc/apache2/ports.conf
      - ./docker/php/conf/sites-enabled:/etc/apache2/sites-enabled

